channels:
  - defaults
dependencies:
  - python=3.10
  - geopandas
  - rsa
  - cmcrameri
  - ipykernel
  - h5py
  - shapely
  - conda-forge::ipywidgets=8
  - ipympl
  - statsmodels
  - matplotlib
  - rasterio
  - earthengine-api
  - rioxarray
  - tzwhere
  - ipyleaflet
  - geopy
  - xarray
  - dask
  - netcdf4
  - conda-forge::tqdm